name: Deploy to Prod Website

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.PULSE_VM_FE_IP }}
          username: ${{ vars.PULSE_VM_FE_USER_NAME }}
          key: ${{ secrets.PULSE_VM_SSH_KEY }}
          port: 22
          source: './'
          target: '/home/azureuser/kaino/apps/kainowebsite'

      - name: deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.PULSE_VM_FE_IP }}
          username: ${{ vars.PULSE_VM_FE_USER_NAME  }}
          key: ${{ secrets.PULSE_VM_SSH_KEY }}
          port: 22
          timeout: 1h
          command_timeout: 1h
          script: |
            cd /home/azureuser/kaino/apps/kainowebsite

            #copy env file
            #sudo cp /home/azureuser/envs/.env.website.prod /home/azureuser/kaino/apps/website/.env

            #docker build
            sudo docker compose build && docker compose down && docker compose up -d
             
            #prune docker images
            sudo docker system prune -f

            
